# Generated by Django 5.2.3 on 2025-09-20 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Talent', '0002_talentspost_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talentspost',
            name='user',
        ),
    ]
